# Compiler flags
# CFLAGS="-O2 -pipe -march=native"
CFLAGS="-O2 -pipe -march=native -fPIC -D_LARGEFILE64_SOURCE=1"
CXXFLAGS="${CFLAGS}"
LDFLAGS="-Wl,--no-as-needed"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"

# CPU cores for parallel builds — set to your core count
MAKEOPTS="-j4"

CHOST="x86_64-pc-linux-gnu"

# Accept keywords and licenses
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="-* @FREE"

